<script setup lang='ts'>

import { usePreloaderStore } from '../../store/preloader.store'
import { watch } from 'vue'

const {isActive} = usePreloaderStore()

</script>

<template>
    <div v-if='isActive' class='fixed right-5 bottom-5 flex items-center'>
        <div class='loadingio-spinner-rolling-l2s5sd4nshf'>
            <div class='ldio-hxzs1ne95mo'>
                <div></div>
            </div>
        </div>
    </div>
</template>

<style lang='scss' scoped>
@keyframes ldio-hxzs1ne95mo {
    0% {
        transform: translate(-50%, -50%) rotate(0deg);
    }
    100% {
        transform: translate(-50%, -50%) rotate(360deg);
    }
}

.ldio-hxzs1ne95mo div {
    position: absolute;
    width: 30px;
    height: 30px;
    border: 7px solid theme("colors.purple.500");;
    border-top-color: transparent;
    border-radius: 50%;
}

.ldio-hxzs1ne95mo div {
    animation: ldio-hxzs1ne95mo 1s linear infinite;
    top: 50px;
    left: 50px
}

.loadingio-spinner-rolling-l2s5sd4nshf {
    width: 44px;
    height: 44px;
    display: inline-block;
    overflow: hidden;
    background: #ffffff;
}

.ldio-hxzs1ne95mo {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(0.44);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
}

.ldio-hxzs1ne95mo div {
    box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>